package com.mmt.record.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mmt.record.mvp.model.entity.FileEntity;
import com.mmt.record.mvp.model.entity.FolderEntity;
import com.mmt.record.mvp.model.entity.GpsEntity;
import com.mmt.record.mvp.model.entity.User;

import com.mmt.record.greendao.FileEntityDao;
import com.mmt.record.greendao.FolderEntityDao;
import com.mmt.record.greendao.GpsEntityDao;
import com.mmt.record.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileEntityDaoConfig;
    private final DaoConfig folderEntityDaoConfig;
    private final DaoConfig gpsEntityDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FileEntityDao fileEntityDao;
    private final FolderEntityDao folderEntityDao;
    private final GpsEntityDao gpsEntityDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileEntityDaoConfig = daoConfigMap.get(FileEntityDao.class).clone();
        fileEntityDaoConfig.initIdentityScope(type);

        folderEntityDaoConfig = daoConfigMap.get(FolderEntityDao.class).clone();
        folderEntityDaoConfig.initIdentityScope(type);

        gpsEntityDaoConfig = daoConfigMap.get(GpsEntityDao.class).clone();
        gpsEntityDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        fileEntityDao = new FileEntityDao(fileEntityDaoConfig, this);
        folderEntityDao = new FolderEntityDao(folderEntityDaoConfig, this);
        gpsEntityDao = new GpsEntityDao(gpsEntityDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(FileEntity.class, fileEntityDao);
        registerDao(FolderEntity.class, folderEntityDao);
        registerDao(GpsEntity.class, gpsEntityDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        fileEntityDaoConfig.clearIdentityScope();
        folderEntityDaoConfig.clearIdentityScope();
        gpsEntityDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FileEntityDao getFileEntityDao() {
        return fileEntityDao;
    }

    public FolderEntityDao getFolderEntityDao() {
        return folderEntityDao;
    }

    public GpsEntityDao getGpsEntityDao() {
        return gpsEntityDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
