package com.mmt.record.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mmt.record.mvp.model.entity.FolderEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FOLDER_ENTITY".
*/
public class FolderEntityDao extends AbstractDao<FolderEntity, Long> {

    public static final String TABLENAME = "FOLDER_ENTITY";

    /**
     * Properties of entity FolderEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FolderPath = new Property(1, String.class, "folderPath", false, "FOLDER_PATH");
        public final static Property AddTime = new Property(2, long.class, "addTime", false, "ADD_TIME");
    }

    private DaoSession daoSession;


    public FolderEntityDao(DaoConfig config) {
        super(config);
    }
    
    public FolderEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FOLDER_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FOLDER_PATH\" TEXT," + // 1: folderPath
                "\"ADD_TIME\" INTEGER NOT NULL );"); // 2: addTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FOLDER_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FolderEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String folderPath = entity.getFolderPath();
        if (folderPath != null) {
            stmt.bindString(2, folderPath);
        }
        stmt.bindLong(3, entity.getAddTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FolderEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String folderPath = entity.getFolderPath();
        if (folderPath != null) {
            stmt.bindString(2, folderPath);
        }
        stmt.bindLong(3, entity.getAddTime());
    }

    @Override
    protected final void attachEntity(FolderEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FolderEntity readEntity(Cursor cursor, int offset) {
        FolderEntity entity = new FolderEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // folderPath
            cursor.getLong(offset + 2) // addTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FolderEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFolderPath(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAddTime(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FolderEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FolderEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FolderEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
